spring:
  datasource:
    password: mypassword
    url: jdbc:postgresql://db:5432/template
    username: template
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: viladevapps@gmail.com
    password: iabn dhoj wpyc zzwu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cors:
  allowed-origins: https://template.dviladev.com
mail:
  enabled: true
  subject:
    account-activation: Account Activation
    password-reset: Password Reset
  message:
    account-activation: Click on the link below to activate your account
    password-reset: Click on the link below to reset your password
auth:
  jwt:
    secret: mysecret
    expiration: 86400000
    issuer: fundshare
  cookie:
    domain: template.dviladev.com
    path: /
    secure: true
    httpOnly: true
    sameSite: Strict
frontend:
  url: https://template.dviladev.com
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
